version: '3'
services:
  api:
    image: api
    build: .
    networks:
      - backend
    environment:
      - SECRET=${SECRET}
      - SERVICES_DOMAINE=${SERVICES_DOMAINE}
      - CORE_DOMAINE=${CORE_DOMAINE}
      - WELL_KNOWN=${WELL_KNOWN}
      - CONF_URL=${CONF_URL}
      - SRV_ID=${SRV_ID}
    ports:
      - "6668:6668"
    volumes:
      - ./logs:/usr/src/logs

networks:
  backend:
    driver: bridge