name: Create API documentation at release publication
on:
  release:
    types:
      - published
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [8]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Set git credentials
              run: |
                  touch ~/.git-credentials
                  git config --global credential.helper 'store --file ~/.git-credentials'
                  echo "https://${{ secrets.GH_USER }}:${{ secrets.GH_PAT }}@github.com" >> ~/.git-credentials
            - name: Run install and apidoc
              run: |
                  npm install
                  npm run apidoc
            - name: Upload apidoc
              uses: actions/upload-artifact@v1
              with:
                  name: apidoc
                  path: apidoc
